/*
 * This source file was generated by the Gradle 'init' task
 */

package palindrometask1;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void testValidPalindrome() {
        SolutionTwo solutionTwo = new SolutionTwo();
        assertEquals(true, solutionTwo.validPalindrome("aba"));
        assertEquals(true, solutionTwo.validPalindrome("abca"));
        assertEquals(false, solutionTwo.validPalindrome("abc"));
    }

    @Test
    public void testIsPalindrome() {
        Solution solution = new Solution();
        assertEquals(true, solution.isPalindrome("A man, a plan, a canal: Panama"));
        assertEquals(false, solution.isPalindrome("race a car"));
        assertEquals(true, solution.isPalindrome(" "));
    }
}
